version: 2.1
workflows:
  version: 2
  commit:
    jobs:
      - build
  weekly:
    triggers:
      - schedule:
          cron: "0 0 * * 1"
          filters:
            branches:
              only:
                - master
jobs:
  build:
    machine:
      docker_layer_caching: false
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t asrob/ubuntu-php-fpm:7.2.19 .
      - run: docker push asrob/ubuntu-php-fpm:7.2.19
